import type {Metadata} from "next";
import Feed from "@/app/(authenticated)/(right-side-bar)/home/components/feed";
import TweetForm from "@/app/(authenticated)/(right-side-bar)/home/components/tweet-form";
import {FeedContentProvider} from "@/app/(authenticated)/(right-side-bar)/home/components/feed-content-provider";
import {HomeHeader} from "@/app/(authenticated)/(right-side-bar)/home/components/home-header";
import {ScrollArea} from "@/components/ui/scroll-area";
import {fetchUser} from "@/lib/server/axios-ssr";
import ClientFallback from "@/app/(authenticated)/components/client-fallback";
import {getAuthenticatedUserId} from "@/lib/server/utils";
import {NavbarMobileTop} from "@/app/(authenticated)/components/navbar-mobile-top";

export const metadata: Metadata = {
    title: "Home / X",
    description: "Generated by create next app",
};

export default async function Home() {

    let user
    try {
        const {data} = await fetchUser(await getAuthenticatedUserId())
        user = data
    } catch (error) {
        return <ClientFallback customErrorMessage={error instanceof Error ? error.message : null}/>
    }

    return (
        <div className="flex flex-col justify-items-stretch items-stretch w-full relative h-screen">
            <FeedContentProvider>
                <NavbarMobileTop/>
                <HomeHeader/>
                <ScrollArea className={"pt-12 pb-12 md:py-0"}>
                    <TweetForm userId={user.id} userAvatar={user.avatar}/>
                    <Feed userId={user.id}/>
                </ScrollArea>
            </FeedContentProvider>
        </div>
    )
}